version: '3.7'

networks:
  services-network:
    name: services-network
    driver: bridge

services:
    planoc-db:
        container_name: planoc-db
        image: postgres:10.5
        restart: always
        environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
        logging:
          options:
            max-size: 10m
            max-file: "3"
        ports:
          - '5432:5432'
        networks:
          - services-network
        volumes: 
          - ./postgres-data:/var/lib/postgresql/data
          # copy the sql script to create tables
          - ./sql/01-users.sql:/docker-entrypoint-initdb.d/01-users.sql
          - ./sql/02-declarations.sql:/docker-entrypoint-initdb.d/02-declarations.sql
          - ./sql/03-redeem.sql:/docker-entrypoint-initdb.d/03-redeem.sql
    planoc:
        container_name: planoc
        restart: always
        build: .
        ports:
          - "9876:9876"
        depends_on:
          - planoc-db
        networks:
          - services-network