version: '3.7'
services:
    service:
        container_name: planoc
        build: .
        ports:
            - "9876:9876"
        depends_on:
          - "postgres"
    postgres:
        container_name: planoc_db
        image: postgres:10.5
        restart: always
        environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
        logging:
          options:
            max-size: 10m
            max-file: "3"
        ports:
          - '5432:5432'
        volumes: 
          - ./postgres-data:/var/lib/postgresql/data
          # copy the sql script to create tables
          - ./sql/01-users.sql:/docker-entrypoint-initdb.d/01-users.sql
          - ./sql/02-declarations.sql:/docker-entrypoint-initdb.d/02-declarations.sql